Blog App: validations and model specs
Aduda-Boaz/rails-blog pull request #3
Opened 2022-07-15 22:17 UTC by Aduda-Boaz

Add unit specs for all of the models' methods and validations.

2022-07-15 23:28 UTC, Gambit142 requested changes
Hi @Aduda-Boaz 👋, 

Good job so far!

## Highlights
- `User`, `Post`, `Comment` and Like model have validations 💯 
- Wrote unit tests for `User`, `Post`, `Comment` and `Like` model 💯 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] The migration files that you have for this milestone are not complete. I noticed that in the migration files, all the columns for each table are missing. The foreign keys and indexes are also missing. Kindly update the migration files because I couldn't run your tests to check if all of them passed. 👍 

_Kindly check the comments under the review for other required changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

#### You can also consider the optional suggestions I made in the comments under the review. I recommend that you implement them because your application won't function properly if they are not implemented. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-07-15 23:28 UTC, Gambit142 commented on spec/models/user_spec.rb
> +  end
- [x] Great work writing this validation test. I noticed that you did not write tests to confirm the presence of attributes for all models. Kindly write validation tests to confirm the presence of attributes for all models (`User`, `Post`, `Comment`, `Like`) created. For example:

```ruby on rails
describe 'validations' do
  it { should validate_presence_of(:name) }
end
```

2022-07-15 23:28 UTC, Gambit142 commented on app/models/post.rb
> +
- [ ] Kindly write validation for the attribute `:like_count`. The `:like_count` must be an integer greater than or equal to zero. 👍

2022-07-15 23:28 UTC, Gambit142 commented on spec/models/post_spec.rb
> +end
- [ ] One of the major project requirements is to write unit tests for all corresponding custom methods in each model. Kindly write a corresponding unit test for the `recent_comments` method in your `Post` model. 👍

2022-07-15 23:28 UTC, Gambit142 commented on spec/models/comment_spec.rb
> +  end
- [ ] [Optional] The `update_post_comments_count` method for which this unit test was written returns the wrong result. It should update the `comments_count` attribute in the `Post` model. 

```ruby on rails
 def update_post_comments_count
    post.increment!(:comments_count)
  end
```

2022-07-15 23:28 UTC, Gambit142 commented on spec/models/post_spec.rb
> +  end
- [ ] [Optional] The `update_post_count` method for which this unit test was written returns the wrong result. It should update the `posts_count` attribute in the `User` model. 

```ruby on rails
 def update_post_count
    user.increment!(:posts_count)
  end
```

2022-07-16 13:20 UTC, aimemalaika approved these changes
Hi @Aduda-Boaz , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7](https://user-images.githubusercontent.com/28307960/158747852-e9f4c957-d810-4de4-b468-69b1337714ea.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-16 13:33 UTC, merged